# Generated by Django 2.1.5 on 2019-01-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeForDisaster', '0002_auto_20190128_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='Coffee', max_length=200),
        ),
    ]
